# Generated by Django 6.0.7 on 2026-07-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_on', models.DateField(auto_now_add=True)),
                ('expected_return', models.DateField()),
                ('returned', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
